### ISSUE TITLE
Error: Can't set headers after they are sent when using file handlebar in docker container

### ISSUE THREAD

**Issue by jimpanzeeee** [fauxauldrich/camouflage#249]
**Describe the bug**
When using [file handlebar](https://testinggospels.github.io/camouflage/handlebars/#file) with [docker camouflage](https://hub.docker.com/r/shubhendumadhukar/camouflage) a "Error: Can't set headers after they are sent" occurs instead of the file being served.

**To Reproduce**
1. Mock File Content 
```
HTTP/1.1 200 OK
Content-Type: image/png

{{file path="./files/mr_man.png"}}
```
2. Folder Structure `camouflage/mocks/aws/s3/student-plans/GET.mock`
3. Error Stack Trace
```
camouflage                  | Error: Can't set headers after they are sent.
camouflage                  |     at SendStream.headersAlreadySent (/usr/local/lib/node_modules/camouflage-server/node_modules/send/index.js:386:13)
camouflage                  |     at SendStream.send (/usr/local/lib/node_modules/camouflage-server/node_modules/send/index.js:613:10)
camouflage                  |     at onstat (/usr/local/lib/node_modules/camouflage-server/node_modules/send/index.js:725:10)
camouflage                  |     at FSReqCallback.oncomplete (node:fs:199:5)
```

**Expected behavior**
The file is served.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [macOS Ventura 13.3]
 - Browser [Using postman not a browser]
 - Version [Not sure what version I am meant to put here]

**Additional context**
Attach camouflage.log file

**Comment by jimpanzeeee** [comment]
Ah I can see this has been [fixed already](https://github.com/testinggospels/camouflage/issues/229), but maybe there hasn't been a docker image update with the same fix?

**Comment by jimpanzeeee** [comment]
Yep - version in docker container is 
```
/app # camouflage --version
0.12.0
```
Could we get a docker image update please?
